[env:cardputer_adv]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = default_8MB.csv
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -DCARDPUTER_ADV_REMOTE
lib_deps =
    https://github.com/m5stack/M5Cardputer.git

[env:cardputer_adv_opt_win]
extends = env:cardputer_adv
build_flags =
    ${env:cardputer_adv.build_flags}
    -DOPT_AS_WIN=1
